### PR TITLE
propose clearly the selected ref?

### PR DESCRIPTION
**Pull request by yoshixmk**

### CODE REVIEW

**Comment by yoshixmk** [comment]
[clabot:check=@yoshixmk]

**Comment by yoshixmk** [comment]
@cla-bot[bot] check

**Comment by yoshixmk** [comment]
@cla-bot help

**Comment by yoshixmk** [comment]
@cla-bot[bot] help

**Comment by yoshixmk** [comment]
[clabot:check]

**Comment by yoshixmk** [comment]
> We require contributors to sign our Contributor License Agreement, and the file is shown on https://github.com/jamashita/turing/blob/master/contributing.md.

[clabot:check]

**Comment by yoshixmk** [comment]
@cla-bot[bot] check

**Comment by jamashita** [comment]
@cla-bot[bot] check

**Comment by yoshixmk** [comment]
[clabot:check]

**Pull request merged**
